name: dev_Pipeline

on: 
  push: 
    branches:
      - main
      - ankita_pytest
  pull_request:
    branches:
      - main  
      - ankita_pytest

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Use the matrix variable here

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('*/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests with Coverage
        run: |
          pytest -n auto --maxfail=1 --cov=. --cov-report=xml

      - name: Upload Coverage Report to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Security Scan with Snyk
        if: github.ref == 'refs/heads/main'
        uses: snyk/actions/setup@main
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        if: github.ref == 'refs/heads/main'
        run: snyk test --file=requirements.txt --severity-threshold=medium