name: dev pipeline

on:
  pull_request:
    branches:
      - main
      - ankita_pytest  
  push:
    branches:
      - main
      - ankita_pytest 

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Running tests on multiple Python versions for compatibility
        python-version: ['3.10', '3.11', '3.12'] 
        cpu: [4] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements-dev.txt  
          pip install -r requirements.txt  

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Run tests with pytest
        run: |
          pytest -n ${{ matrix.cpu }} --cov --cov-report=xml  
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3  
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  
        if: always()  