name: dev_Pipeline
on: 
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main  
jobs:
  check:
    runs-on: ubuntu-latest

    # Use the maximum number of CPUs available
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests
        run: |
          pytest -n auto --maxfail=1 --cov=. --cov-report=xml


      - name: Upload Coverage Report to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Security Scan with Snyk
        uses: snyk/actions/setup@v3
        with:
          token: ${{secrets.SNYK_TOKEN }}

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-