name: dev pipeline

on:
  pull_request:
    branches:
      - ankita_pytest  # Run tests on pull requests to this branch
  push:
    branches:
      - main 
        - ankita_pytest  # Run security scan on every push to main

jobs:
  # Job to run tests and measure coverage
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version, e.g., 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist  # Install pytest tools

      - name: Run tests with pytest in parallel
        run: pytest -n auto --cov=.  # -n auto uses all available CPUs for parallel tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Ensure CODECOV_TOKEN is set in GitHub Secrets

  # Job to run Snyk security scan on main branch
  snyk:
    needs: test  # Run after test job completes
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Ensure SNYK_TOKEN is set in GitHub Secrets