name: dev pipeline

on:
  pull_request:
    branches:
      - main
      - ankita_pytest  
  push:
    branches:
      - main 
      - ankita_pytest

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpu: [2, 4, 8]  # Use multiple CPUs to speed up pytest run
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Set your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest -n ${{ matrix.cpu }} --cov --cov-report=xml  # Use the matrix value for number of CPUs to run tests in parallel

      # Optionally: Upload coverage report to Codecov or Code Climate
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        if: always()
