name: Build, Scan and Push Docker File

on:
  pull_request:
    branches:
      - main
      - kiran_pytest  
  push:
    branches:
      - main
      - kiran_pytest 

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements.txt --sarif-file-output=snyk.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif 

  build_and_push:
    runs-on: ubuntu-latest
    needs: security-scan  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure Docker is Running
        run: |
          sudo service docker start
          docker info 

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/hs-heilbronn-devsecops-team-ak/note-api:latest  

  Deploy-to-Google-Cloud-Run:
    runs-on: ubuntu-latest
    needs: build_and_push
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
  
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'
  
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'note-api'
  
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet
  
      - name: Build Docker image for Artifact Registry
        run: |
          docker build -t europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api/main:latest .
  
      - name: Tag and Push Docker image to Artifact Registry
        run: |
          docker tag europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api/main:latest \
          europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-Team-ak/note-api/main:latest
          docker push europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-Team-ak/note-api/main:latest
  
      - name: Deploy Docker image to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'note-api-hs-heilbronn-devsecops-Team-ak'
          image: 'europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-Team-ak/note-api/main:latest'
          region: 'europe-west3'
          env_vars: BACKEND=memory
